runtime: python27
service: gora
network:
  name: test-prod-270304/global/networks/testvpc
  subnetwork_name: testsub
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"