runtime: python27
service: gora
network:
  name: testvpc
  subnetwork_name: testsub
  session_affinity: true

api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"