runtime: python27
service: gora
vpc_access_connector:
  name: "test-prod/test-prod-270304/us-central/us-central1/connectors/testvpc"

api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"